### ISSUE TITLE
Missing package dependency 'zlib-browserify'

### ISSUE THREAD

**Issue by jthomas** [moimikey/iso3166-1#5]
```
> var iso3166 = require('iso3166-1')
Error: Cannot find module 'zlib-browserify'
    at Function.Module._resolveFilename (module.js:336:15)
    at Function.Module._load (module.js:278:25)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (/Users/james/Code/BlueMix/stack-overflow/node_modules/iso3166-1/src/index.js:2:14)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
```

**Comment by moimikey** [comment]
eek sorry for the delay in response. hm. that's odd, `zlib-browserify` should be available after doing an `npm install`. is it not present in `node_modules?` @jthomas

**Comment by moimikey** [comment]
ah shiz, i know what the problem is. fixing!

**Comment by moimikey** [comment]
@jthomas all grand now! just update to the latest and it should work :)

**Comment by jthomas** [comment]
thanks!
